name: Daily Google Play Review Scraper

on:
  schedule:
    - cron: '0 5 * * *'  # 한국 오후 2시 (KST)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install google-play-scraper pandas requests

      - name: Run scraper
        run: python daily_scraper.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Upload results artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: scraped-reviews
          path: reviews_*.csv
